### PR TITLE
Updates for GA.

### PR DESCRIPTION
**Pull request by alderete-sfdc**
Restore deleted general (non-pilot) intro.
Update Salesforce DX language, and GA status.
Update Salesforce DX installation steps.
Update references to Jasmine resources that were renamed.
Add references to Mocha resources.

### CODE REVIEW

**Comment by esalman-sfdc** [comment]
Will we write up consumer flow (e.g. talk about 'force:lightning:test:install' via a follow up doc? @mleonardsfdc

**Comment by mleonardsfdc** [comment]
@esalman-sfdc I don't have much context on this feature. Did you mean to mention @alderete-sfdc ?

**Comment by esalman-sfdc** [comment]
oops yes, message was meant for @alderete-sfdc  :)

**Comment by alderete-sfdc** [comment]
I am in progress on further updates to add more details. I thought test:install was already documented, but perhaps not as thoroughly as it might be. (I just checked and it's missing from the SFDX command line reference.) I'll add it to the list...

**Comment by alderete-sfdc** [comment]
@esalman-sfdc @cdengSFDC OK, reading comprehension fail. I only yesterday noticed that force:lightning:test:install was different from force:package:install. It was just "force:blah:blah:install" in my eyes.

I've committed another revision that re-arranges things, and makes installing using SFDX the happy, preferred path. Let me know if this looks good.

I'm trying to get this minimal update in for GA before I start on some significant refactoring / re-arranging of the doc, into shorter, separate topics. (That'll take a few days, at least.)

**Comment by alderete-sfdc** [comment]
Hey @esalman-sfdc what's the status of getting this pull request merged?

I do have plenty more work to do on doc for LTS (and LWCs), but the changes here are self-contained, and worth getting into the public view.

**Pull request merged**
